### PR TITLE
Add schema files

### PR DESCRIPTION
**Pull request by Alabi12**
### Pull Request Summary
- [ ] Create a new app. Give it a meaningful name.

- Initialize your project with Git.

- Make sure that your project has Postgres database set up.

- Build your project schema.

- [ ] Create and run the necessary migration files.

- Table and column names should match the ERD diagram. **NB**: photo for users table should be a link to an image

- Foreign keys should be included.

- All columns that are foreign keys should have a corresponding index.

### CODE REVIEW

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Alabi12,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Your project does not follow the required workflow. You are required to work on a feature branch and compare it to the dev branch, but you worked on the dev branch and compared it to the main branch. Kindly fix that.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by FrederickMih — COMMENTED** [review]
## Hi :raising_hand: , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**As requested above, let's follow the correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by FrederickMih** [comment]
@Alabi12, do you find it difficult to follow the correct Gitflow? Can I assist you?

You just submitted the same PR with the wrong Gitflow a few minutes after I invalid it :angry:

**Comment by Alabi12** [comment]
I get it now. Thanks will fix it and resubmit it

**Pull request merged**
